# Generated by Django 4.1.7 on 2023-05-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Prenom')),
                ('surname', models.CharField(max_length=30, verbose_name='Nom')),
                ('birthday', models.DateTimeField(verbose_name='Date de Naissance')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('studentname_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.studentname')),
                ('username', models.CharField(default='', max_length=50, verbose_name='Username')),
                ('nationality', models.CharField(default='française', max_length=50, verbose_name='Nationalite')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Adresse mail')),
                ('address', models.CharField(max_length=200, verbose_name='Adresse')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='N° téléphone')),
                ('studies', models.CharField(choices=[('sciences', 'Sciences'), ('geopo', 'Géopolitique'), ('histoire', 'Histoire'), ('litterature', 'Littérature'), ('psycho', 'Psychologie'), ('sante', 'Santé'), ('socio', 'Sociologie'), ('menuiserie', 'Menuiserie'), ('gastronomie', 'Gastronomie'), ('bio', 'Biologie')], default=None, max_length=50, verbose_name="Domaine d'études")),
                ('level', models.CharField(choices=[('bac', 'Bac'), ('bts', 'BTS'), ('cap', 'CAP'), ('bep', 'BEP'), ('l1', 'Licence 1'), ('l2', 'Licence 2'), ('l3', 'Licence 3'), ('m1', 'Master 1'), ('m2', 'Master 2'), ('doctorat', 'Doctorat'), ('brevet', 'Brevet des collèges')], default=None, max_length=50, verbose_name="Niveau d'études")),
            ],
            bases=('student.studentname',),
        ),
        migrations.CreateModel(
            name='StudentFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('nb_payments', models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentname')),
            ],
        ),
    ]
