# Generated by Django 4.1.7 on 2023-03-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_basestudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='BaseStudent',
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('bac', 'Bac'), ('bts', 'BTS'), ('cap', 'CAP'), ('bep', 'BEP'), ('l1', 'Licence 1'), ('l2', 'Licence 2'), ('l3', 'Licence 3'), ('m1', 'Master 1'), ('m2', 'Master 1'), ('doctorat', 'Doctorat'), ('brevet', 'Brevet des collèges')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='studies',
            field=models.CharField(choices=[('sciences', 'Sciences'), ('geopo', 'Géopolitique'), ('histoire', 'Histoire'), ('litterature', 'Littérature'), ('psycho', 'Psychologie'), ('sante', 'Santé'), ('socio', 'Sociologie'), ('menuiserie', 'Menuiserie'), ('gastronomie', 'Gastronomie'), ('bio', 'Biologie')], default=None, max_length=50),
        ),
    ]
