# Generated by Django 4.1.7 on 2023-04-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_listings_delete_basestudent_student_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateTimeField(verbose_name='Date de Naissance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Adresse mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('bac', 'Bac'), ('bts', 'BTS'), ('cap', 'CAP'), ('bep', 'BEP'), ('l1', 'Licence 1'), ('l2', 'Licence 2'), ('l3', 'Licence 3'), ('m1', 'Master 1'), ('m2', 'Master 2'), ('doctorat', 'Doctorat'), ('brevet', 'Brevet des collèges')], default=None, max_length=50, verbose_name="Niveau d'études"),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='N° téléphone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studies',
            field=models.CharField(choices=[('sciences', 'Sciences'), ('geopo', 'Géopolitique'), ('histoire', 'Histoire'), ('litterature', 'Littérature'), ('psycho', 'Psychologie'), ('sante', 'Santé'), ('socio', 'Sociologie'), ('menuiserie', 'Menuiserie'), ('gastronomie', 'Gastronomie'), ('bio', 'Biologie')], default=None, max_length=50, verbose_name="Domaine d'études"),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Prénom'),
        ),
    ]
