# Generated by Django 4.1.7 on 2023-04-05 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_delete_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('surname', models.CharField(max_length=30, verbose_name='Prénom')),
                ('birthday', models.DateTimeField(verbose_name='Date de Naissance')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.CreateModel(
            name='StudentInformations',
            fields=[
                ('studentname_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.studentname')),
                ('email', models.EmailField(max_length=30, verbose_name='Adresse mail')),
                ('address', models.CharField(max_length=200, verbose_name='Adresse')),
                ('phone', models.CharField(max_length=10, verbose_name='N° téléphone')),
                ('studies', models.CharField(choices=[('sciences', 'Sciences'), ('geopo', 'Géopolitique'), ('histoire', 'Histoire'), ('litterature', 'Littérature'), ('psycho', 'Psychologie'), ('sante', 'Santé'), ('socio', 'Sociologie'), ('menuiserie', 'Menuiserie'), ('gastronomie', 'Gastronomie'), ('bio', 'Biologie')], default=None, max_length=50, verbose_name="Domaine d'études")),
                ('level', models.CharField(choices=[('bac', 'Bac'), ('bts', 'BTS'), ('cap', 'CAP'), ('bep', 'BEP'), ('l1', 'Licence 1'), ('l2', 'Licence 2'), ('l3', 'Licence 3'), ('m1', 'Master 1'), ('m2', 'Master 2'), ('doctorat', 'Doctorat'), ('brevet', 'Brevet des collèges')], default=None, max_length=50, verbose_name="Niveau d'études")),
            ],
            bases=('student.studentname',),
        ),
    ]
