# Generated by Django 4.1.7 on 2023-04-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentname_delete_student_studentinformations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformations',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='Adresse mail'),
        ),
        migrations.AlterField(
            model_name='studentinformations',
            name='phone',
            field=models.CharField(max_length=10, unique=True, verbose_name='N° téléphone'),
        ),
    ]
