# Generated by Django 4.1.7 on 2023-04-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentinformations_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentInformations',
            new_name='StudentInformation',
        ),
        migrations.AlterField(
            model_name='studentname',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='studentname',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.CreateModel(
            name='StudentFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('nb_payments', models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentname')),
            ],
        ),
    ]
